"""empty message

Revision ID: 38b7a1032bdd
Revises: c763cdb7a96c
Create Date: 2017-11-30 08:56:11.787860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b7a1032bdd'
down_revision = 'c763cdb7a96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('start_url', sa.String(length=512), nullable=True),
    sa.Column('brokenLinkList', sa.JSON(), nullable=True),
    sa.Column('last_check_datetime', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
