"""empty message

Revision ID: 48aef8232795
Revises: 93112ff3d1fb
Create Date: 2017-12-05 07:18:12.918450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aef8232795'
down_revision = '93112ff3d1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_datetime', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_datetime')
    # ### end Alembic commands ###
